---
title: "Examples on the MRSea website"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples on the MRSea website}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE,include=FALSE}
```

## Package examples

These examples/tutorials are available at (https://lindesaysh.github.io/MRSea)

```{r, echo=FALSE,results="asis"}
files <- list.files("web", "\\.Rmd$")
for (file in file.path("web", files)) {
  lines <- readLines(file, n = 10)
  title_idx <- grep("^title: ", lines)
  if (length(title_idx) > 0) {
    title <- sub("^title: ", "", lines[title_idx[1]])
    title <- sub('^"', "", title)
    title <- sub('"$', "", title)
    cat("* [",
      title,
      "](https://lindesaysh.github.io/MRSea/articles/",
      sub("\\.Rmd", ".html", file),
      ")\n",
      sep = ""
    )
  }
}
```

## Package vignettes

These package vignettes are also available at (https://lindesaysh.github.io/MRSea)

```{r, echo=FALSE,results="asis"}
files <- list.files(".", "\\.Rmd$")
for (file in files) {
  lines <- readLines(file, n = 10)
  title_idx <- grep("^title: ", lines)
  if (length(title_idx) > 0) {
    title <- sub("^title: ", "", lines[title_idx[1]])
    title <- sub('^"', "", title)
    title <- sub('"$', "", title)
    cat("* [",
      title,
      "](https://lindesaysh.github.io/MRSea/articles/",
      sub("\\.Rmd", ".html", file),
      ")\n",
      sep = ""
    )
  }
}
```
